[profile.default]
src = 'contracts'
out = 'artifacts_forge'
libs = ['node_modules', 'lib']
test = 'test/pnm'
cache_path  = 'cache_forge'
gas_reports = ["TradePool", "DigitalPayoffPool", "ChainlinkAdapter"]
