/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOracleAdapter,
  IOracleAdapterInterface,
} from "../../../contracts/rate/IOracleAdapter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "idx",
        type: "uint256",
      },
    ],
    name: "getLatestPrice",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOracleAdapter__factory {
  static readonly abi = _abi;
  static createInterface(): IOracleAdapterInterface {
    return new utils.Interface(_abi) as IOracleAdapterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOracleAdapter {
    return new Contract(address, _abi, signerOrProvider) as IOracleAdapter;
  }
}
