/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DigitalPayoffPool } from "./DigitalPayoffPool";
export type { IPayoffPoolPlugin } from "./IPayoffPoolPlugin";
