/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChainlinkAdapter } from "./ChainlinkAdapter";
export type { IOracleAdapter } from "./IOracleAdapter";
export type { MockOracleAdapter } from "./MockOracleAdapter";
